# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms will be:

        # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def sum_of_fibonacci_series():
    num1 = 0
    num2 = 1
    num3 = num1 + num2
    sum = 0

    for i in range(1, 100):
        if num3 <= 4000000:
            if num3 % 2 == 0:
                sum += num3
            num1 = num2
            num2 = num3
            num3 = num1 + num2
    print(num3)
    print(sum)
    return
    
sum_of_fibonacci_series()

